server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
          apple:
            client-id: ${APPLE_CLIENT_ID}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1일
  refreshExpiration: 2592000000 # 30일

oauth:
  apple:
    client-ids:
      - com.stitch.JikgwanEottae.SignIn
    issuer: https://appleid.apple.com
    jwks-uri: https://appleid.apple.com/auth/keys
    team-id: ${APPLE_TEAM_ID}
    key-id: ${APPLE_KEY_ID}
    p8-b64: ${APPLE_P8_B64}

tourism:
  area:
    service-key: ${TOURISM_AREA_SERVICE_KEY}
    base-url: https://apis.data.go.kr/B551011/KorService2
  relate:
    service-key: ${TOURISM_RELATE_SERVICE_KEY}
    base-url: https://apis.data.go.kr/B551011/TarRlteTarService1

fastapi:
  base-url: ${FASTAPI_BASE_URL}

cache:
  calendar:
    warm-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"
      probes:
        enabled: true

management.health.db.enabled: false

